### ISSUE TITLE
Mozilla Firefox Chat Bug

### ISSUE THREAD

**Issue by Rapmig** [Aedificem/ontrac#124]

**Comment by Rapmig** [comment]
OKAY I ALREADY EXPLAINED ABOUT THE LOUD DING OF DEATH..... NOW GET TO WORK AND FIX IT

**Comment by Apexal** [comment]
I cannot replicate on my desktop nor Chromebook

**Comment by Rapmig** [comment]
It fixed itself from before... (When u made the small speed changes yesterday)
